### ISSUE TITLE
BES - Device info

### ISSUE THREAD

**Issue by Zimtir** [future-code-lab/botnet#24]
Нам надо понимать размеры, версию ОС, а также модель девайса, который нам отдадут для MVP

**Comment by jskonst** [comment]
Digma CITI 1901 4G

**Comment by egordunaev** [comment]
Согласно порталу [digma](https://digma.ru/catalog/item/2080), диагональ экрана 10.1" (25,7 см), думаю это нужно иметь ввиду при создании тех же мокапов в фигме.
Also, @Zimtir стоит ли добавить в проект какой нибудь `.md` со всей информацией о планшете чтобы не потерять?

**Comment by Zimtir** [comment]
@egordunaev думаю да, было бы не плохо!

**Comment by egordunaev** [comment]
@Zimtir 
![image](https://user-images.githubusercontent.com/29885771/123165513-0122f200-d47d-11eb-819f-24e1b0cfe316.png)
Не могу запушить свою ветку на PR, что-то не так с доступом?

**Comment by Zimtir** [comment]
> @Zimtir
> ![image](https://user-images.githubusercontent.com/29885771/123165513-0122f200-d47d-11eb-819f-24e1b0cfe316.png)
> Не могу запушить свою ветку на PR, что-то не так с доступом?

fixed! :) спасибо за уведомление!

**Comment by egordunaev** [comment]
Написал страничку, сделал PR #25 
Please review 😄

**Comment by Zimtir** [comment]
> Написал страничку, сделал PR #25
> Please review 😄

Done :) PTAL again
