### ISSUE TITLE
BS - Server

### ISSUE THREAD

**Issue by Zimtir** [future-code-lab/botnet#5]
We should have a server

**Comment by Zimtir** [comment]
@Uzhastin-Nikita 

Нам понадобится сделать бота который обрабатывает вход и выход 

Причём выход может быть куда угодно 

Почитай про паттерн Адаптер

Сейчас твоя задача следующая 

- Сделать простого бота с контекстом, который работает на уровне терминала

Потом будем к нему прикручивать телегу, вк, веб чат версию



Твоя часть на проекте - это обработка сообщений 

По сути, вот перед тобой стоит робот, человек может с ним разговаривать устно, может написать ему в телегу, может написать в вк 
Может просто API пинать

Вот твоя текущая задача - простой бот с которым можно общаться в терминале, он будет отвечать одинаково например всегда, но основная цель - сохранить контекст сообщений

**Comment by Uzhastin-Nikita** [comment]
Можешь подробнее объяснить про Контекст сообщений?

**Comment by Uzhastin-Nikita** [comment]
Просто чисто эхо-бота я запил, пишешь ему Привет - он тебе в ответ привет, пишешь 'Ты плохой', а он тебе в ответ то же самое.

**Comment by Zimtir** [comment]
> Можешь подробнее объяснить про Контекст сообщений?

Имеется в виду сессии сообщений, чтобы он имел у себя в запасе на момент разговора предыдущие сообщения, ты ему:

- Привет, я из города Иваново
- Скажи погоду

И чтобы он потом не задавал вопрос "А какой у вас город?"
Но давай это в отдельный таск закину потом

**Comment by Zimtir** [comment]
> Просто чисто эхо-бота я запил, пишешь ему Привет - он тебе в ответ привет, пишешь 'Ты плохой', а он тебе в ответ то же самое.

Отлично, давай Pull Request
