### ISSUE TITLE
BS - Telegram

### ISSUE THREAD

**Issue by Zimtir** [future-code-lab/botnet#6]

**Comment by Uzhastin-Nikita** [comment]
Начал делать тг, возникли небольшие проблемы с импортом server.py, почему-то не видит функцию внутри него

**Comment by Uzhastin-Nikita** [comment]
Так, с проблемой выше я разобрался, но теперь проблема в том, что на любое сообщение он отвечает, что Не понимает и если использовать `lower()`, `strip()`, то тоже не работает :(

**Comment by Uzhastin-Nikita** [comment]
Теперь он отвечает на односложные сообщения, но почему-то на запрос `Как дела?` - отвечает, что Не понимает, хотя обработку на удаление знаков препинания я написал.
Сегодня залью pr, взглянете, может заметите проблему быстрее, чем я

**Comment by Uzhastin-Nikita** [comment]
С проблемой выше разобрался, но придется избавится от Цикла.
Осталось засунуть токен в переменную окружения и готово

**Comment by Uzhastin-Nikita** [comment]
![image](https://user-images.githubusercontent.com/71666299/126631506-059e1dd1-d6fa-4143-a56a-3e03ff51126e.png)

Что это за штука такая?
