### ISSUE TITLE
BS - Docker

### ISSUE THREAD

**Issue by Zimtir** [future-code-lab/botnet#8]

**Comment by egordunaev** [comment]
Хотел уточнить что именно будем делать с докером, можно поинтами. 🤔

**Comment by Uzhastin-Nikita** [comment]
@egordunaev но в целом нам можно уже начинать что-то делать с докером, эхо-бот есть

**Comment by Zimtir** [comment]
> Хотел уточнить что именно будем делать с докером, можно поинтами. 🤔

- Билдить для GitHub Actions (просто чтобы убедиться что сборка проходит)
- Публиковать образ в GitHub Container Registry
- Иметь возможность работать Dev-in-Container
- Иметь возможность запускаться через docker-compose
@egordunaev @Uzhastin-Nikita

**Comment by egordunaev** [comment]
@Zimtir для некоторых экшонов типа "Publish Docker Image" и т.д. мне нужно сделать пару сикретов, я так понял доступа на их создание у меня нет?

**Comment by Zimtir** [comment]
> @Zimtir для некоторых экшонов типа "Publish Docker Image" и т.д. мне нужно сделать пару сикретов, я так понял доступа на их создание у меня нет?

Скажи какие сделать - сделаю, к сожалению тут с настройками доступа, довольно, не так лояльно, как хотелось бы
Либо я могу временно выдать доступ, а потом убрать, что думаешь на этот счет?

**Comment by egordunaev** [comment]
Я лучше тогда подготовлю список какие сикреты нужно будет сделать и потом предоставлю его тебе.
